Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Models/CustomerViewModel.cs
namespace Web_CNPMNC_DA_HeThongATM.Models
{
    public class CustomerViewModel
    {
        public string CCCD { get; set; }
        public string Diachi { get; set; }
        public string Email { get; set; }
        public string Gioitinh { get; set; }
        public string Makh { get; set; }
        public string Sdt { get; set; }
        public string Tenkh { get; set; }
    }
}

Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Web_CNPMNC_DA_HeThongATM.Models;
using Web_CNPMNC_DA_HeThongATM.Models.ClassModel;
using Web_CNPMNC_DA_HeThongATM.Models.ViewModel;

namespace Web_CNPMNC_DA_HeThongATM.Controllers
{
    public class CustomerController : Controller
    {
        FirebaseHelper firebaseHelper;

        public CustomerController()
        {
            firebaseHelper = new FirebaseHelper();
        }
        // Danh sách khách hàng
        public IActionResult Index()
        {
            List<KhachHang> khachHangs = firebaseHelper.GetCustomers();
            List<KhachHangViewModel> khachHangViewModels = new List<KhachHangViewModel>();
            foreach (var i in khachHangs)
            {
                var pro = new KhachHangViewModel
                {
                    CCCD = i.CCCD,
                    DiaChi = i.DiaChi,
                    Email = i.Email,
                    GioiTinh = i.GioiTinh,
                    SoDienThoai = i.SoDienThoai,
                    TenKH = i.TenKH,
                    NgayTao = i.NgayTao,
                };
                
                khachHangViewModels.Add(pro);
            }

            ViewData["j"] = khachHangViewModels;

            return View();
        }
        [HttpGet]
        public IActionResult DetailsCustomer(string CCCD)

        {

            KhachHang khachhang = firebaseHelper.GetCustomerbyid(CCCD);

            ViewBag.TenKhachHang = firebaseHelper.GetNameCustomerbyid(CCCD);

            ViewBag.Details = khachhang;

            return View();

        }
        [HttpPost]

        public IActionResult DetailsCustomer(KhachHangViewModel khachhang)

        {

            return View();

        }
        public IActionResult CreateCustommer()
        {
            return View();
        }

        //tạo khách hàng
        [HttpPost]
        public IActionResult CreateCustommer(KhachHangViewModel customer)
        {

            customer.MatKhau = firebaseHelper.PassRandom();
            ModelState.Remove("MatKhau");
            ModelState.Remove("MaNhanVienKey");
            if (ModelState.IsValid)
            {

                firebaseHelper.InsertCustommer(customer);

                return RedirectToAction("Index");
            }

            return View("CreateCustommer", customer);

        }

        //check cccd
        [HttpGet]
        public async Task<IActionResult> CheckCanCuoc(string cccd)
        {

            var idcccd = await firebaseHelper.CheckCCCDExist(cccd);
            Console.WriteLine(idcccd);
            return Json(idcccd);
        }

        //check sdt
        [HttpGet]
        public IActionResult CheckSdt(string Sdt)
        {
            bool CheckSdt = firebaseHelper.CheckSdt(Sdt);

            return Json(CheckSdt);
        }

        public IActionResult SearchCustomer(string searchCustomer)
        {

            KhachHang khachHang = firebaseHelper.SearchCustomer(searchCustomer);
            KhachHangViewModel ViewThes = new KhachHangViewModel();
            ViewThes.CCCD = khachHang.CCCD;
            ViewThes.TenKH = khachHang.TenKH;
            ViewThes.NgayTao = khachHang.NgayTao;
            ViewThes.Email = khachHang.Email;
            ViewThes.SoDienThoai = khachHang.SoDienThoai;
            ViewThes.GioiTinh = khachHang.GioiTinh;
            ViewThes.DiaChi = khachHang.DiaChi;
            ViewBag.IteamSeach = ViewThes;
            return PartialView("SearchCustomer");
        }
        //public IActionResult EditCustomer(string CCCD)
        //{
        //    firebaseHelper.GetCustomerbyid(CCCD);
        //    return View();
        //}

        //[HttpPost]
        //public IActionResult EditCustomer(KhachHangViewModel customer)
        //{
        //    firebaseHelper.EditCustomer(customer.CCCD, customer);
        //    return RedirectToAction("Index");
        //}
    }
}

Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Controllers/CustomerServiceController.cs
using Microsoft.AspNetCore.Mvc;
using Web_CNPMNC_DA_HeThongATM.Models;
using Web_CNPMNC_DA_HeThongATM.Models.ClassModel;

using Web_CNPMNC_DA_HeThongATM.Models.ViewModel;

namespace Web_CNPMNC_DA_HeThongATM.Controllers
{
    public class CustomerServiceController : Controller
    {
        string TenTK;
        string accountKey;

        FirebaseHelper firebaseHelper = new FirebaseHelper();

        // Rút tiền
        [HttpGet]
        public IActionResult RutTien()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RutTien(TaiKhoanLienKetViewModel account)
        {
            double sotien = (double)account.SoTien;
            firebaseHelper.RutTien(sotien, (long)account.SoTaiKhoan);
            return RedirectToAction("RutTien");
        }

        public IActionResult ChuyenTien(IFormCollection form)
        {
            // Lấy dữ liệu từ form
            double soTien = Convert.ToDouble(form["SoTien"]);
            long taiKhoanNguoiChuyen = Convert.ToInt64(form["SoTaiKhoanNguoiChuyen"]);
            long taiKhoanNguoiNhan = Convert.ToInt64(form["SoTaiKhoanNguoiNhan"]);

            // Tiếp tục xử lý chuyển tiền
            firebaseHelper.ChuyenTien(soTien, taiKhoanNguoiChuyen, taiKhoanNguoiNhan);

            ViewData["ChuyenTienSuccess"] = true;

            return View();
        }

        [HttpGet]
        public IActionResult sendAccount(long SoTaiKhoan)
        {
            string tinhtrang = "undefined";
            if (firebaseHelper.GetAccountbyid(SoTaiKhoan) != null)
            {
                TenTK = firebaseHelper.GetAccountbyid(SoTaiKhoan).TenTK;
                return Json(TenTK);
            }
            else
            {
                return Json("Không tìm thấy");
            }
        }

        // Nạp tiền
        public IActionResult NapTien()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NapTien(TaiKhoanLienKetViewModel account)
        { 
            ModelState.Remove("Key");
            ModelState.Remove("MaKHKey");
            ModelState.Remove("MaLoaiTKKey");
            ModelState.Remove("TenTK");

			if (ModelState.IsValid)
            {
				double sotien = (double)account.SoTien;

				firebaseHelper.NapTien(sotien, (long)account.SoTaiKhoan,(long)account.SoTaiKhoan);

				TempData["Message"] = "Đặt Lịch Hẹn";

				return RedirectToAction("NapTien");
			}

			TempData["Fail"] = "Đặt Lịch Hẹn";

			return View("NapTien", account);
        }
    }
}

Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Views/Customer/CreateCustommer.cshtml
@using Web_CNPMNC_DA_HeThongATM.Models.ViewModel
@model KhachHangViewModel
@{
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
<body>
    @if (TempData["Message"] != null)
    {
        <div class="sufee-alert alert with-close alert-primary alert-dismissible fade show">
            <span class="badge badge-pill badge-primary">Thành Công</span>
            @TempData["Message"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
    }
    else if (TempData["Fail"] != null)
    {
        <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
            <span class="badge badge-pill badge-danger">Thất Bại</span>
            @TempData["Fail"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
    }
    <div id="custom-dialog" title="Thông báo" style="display: none;"></div>

    <form method="post" asp-controller="Customer" asp-action="CreateCustommer" >
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header"><strong>CusTomer</strong></div>
                <div class="card-body card-block">
                    <div class="form-group">

                        <label for="company" class=" form-control-label">Mã Căn Cước Công Dân</label>
                        <input type="number" asp-for="CCCD" id="cccd" class="form-control">
                    </div>
                   
                    <span asp-validation-for="CCCD" class="text-danger text-validation"></span>
                    <div class="row form-group">
                       
                        <div class="col-md-6">
                            <label for="vat" class="form-control-label">Tên Khách Hàng</label>
                            <input type="text" asp-for="TenKH" class="form-control">
                            <span asp-validation-for="TenKH" class="text-danger text-validation"></span>
                        </div>
                        <div class="col-md-3">
                            <label for="vat" class="form-control-label">Ngày Sinh</label>
                            <input type="date" asp-for="NgaySinh" class="form-control">
                            <span asp-validation-for="NgaySinh" class="text-danger text-validation"></span>
                        </div>
                        <div class="col-md-3">
                            <div>
                                <label class=" form-control-label">Giới tính</label>

                            </div>
                            <div>
                                <div class="form-check-inline form-check">
                                    <label for="inline-radio1" class="form-check-label col-md-7">
                                        <input type="radio" id="inline-radio1" name="Gioitinh" value="Nam" asp-for="GioiTinh" class="form-check-input">Nam
                                    </label>
                                    <label for="inline-radio2" class="form-check-label col-md-6">
                                        <input type="radio" id="inline-radio2" name="Gioitinh" value="Nữ" asp-for="GioiTinh" class="form-check-input">Nữ
                                    </label>
                                </div>

                            </div>
                            <span asp-validation-for="GioiTinh" class="text-danger text-validation"></span>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="sonha" class="form-control-label">Số nhà:</label>
                            <input type="text" id="sonha" class="form-control">
                        </div>
                        <div class="col-md-3">
                            <label for="phuongxa" class="form-control-label">Phường/Xã:</label>
                            <input type="text" id="phuongxa" class="form-control">
                        </div>
                        <div class="col-md-3">
                            <label for="quanhuyen" class="form-control-label">Quận/Huyện:</label>
                            <input type="text" id="quanhuyen" class="form-control">
                        </div>
                        <div class="col-md-3">
                            <label for="tinhthanh" class="form-control-label">Tỉnh/Thành phố:</label>
                            <input type="text" id="tinhthanh" class="form-control">
                        </div>
                        <input type="hidden" asp-for="DiaChi" id="Diachi" class="form-control">
                        <span asp-validation-for="DiaChi" class="text-danger text-validation col-md-3"></span>
                    </div>

                    <div class="row form-group">
                        <div class="col-md-6">
                            <label for="country" class=" form-control-label">Email</label>
                            <input type="email" asp-for="Email" class="form-control">
                            <span asp-validation-for="Email" class="text-danger text-validation"></span>
                        </div>
                        <div class="col-md-6">
                            <label for="country" class=" form-control-label">Số Điện Thoại</label>
                            <input type="number" id="Sdt" asp-for="SoDienThoai" class="form-control">
                            <span asp-validation-for="SoDienThoai" class="text-danger text-validation"></span>
                        </div>
                    </div>
                    <input hidden asp-for="NgayTao" id="NgayTao" />
                    <div class="form-actions form-group" style="margin-top:4px">
                        <button style="width:100%;font-size:20px" type="submit" class="btn btn-primary btn-sm">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="/js/form-custommer.js"> </script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</body>

Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Views/Customer/DetailsCustomer.cshtml
﻿@using Web_CNPMNC_DA_HeThongATM.Models.ViewModel

@model KhachHangViewModel

@{
    Layout = "_LayoutMain";

}
<div class="col-md-12" style="height:100vh">
   
    <div class="container col-md-10">
        <form method="post" asp-controller="Customer" asp-action="Details" style="padding-top:0px ; background-color:#ffff">
            <div class="inputBox">
                <span class="col-md-5">
                    Chi Tiết Khách Hàng
                </span>
            </div>
            
            <div class="flexbox">

                <div class="inputBox">
                    <span>
                        Mã Khách Hàng
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>
                    <input readonly value="@ViewBag.Details.CCCD" type="text" maxlength="16" id="makhachhang" asp-for="CCCD">
                </div>
                <div class="inputBox">
                    <span>
                        Tên Khách Hàng
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>
                    <input type="text" class="text-input" readonly value="@ViewBag.Details.TenKH" type="text" maxlength="16" class="sdt" asp-for="TenKH">
                </div>
            </div>
            <div class="flexbox">
                <div class="inputBox">
                    <span>
                        Giới Tính
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>
                    <input type="text" class="text-input" readonly value="@ViewBag.Details.GioiTinh" type="text" maxlength="16" class="sdt" asp-for="GioiTinh">
                </div>              
                <div class="inputBox">
                    <span>
                        Số Điện Thoại
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>
                    <input type="text" class="text-input" value="@ViewBag.Details.SoDienThoai" type="text" class="card-holder-input" asp-for="SoDienThoai">

                </div>
            </div>
            <div class="flexbox">
                <div class="inputBox">
                    <span>
                        Email
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>
                    <input type="text" class="text-input" value="@ViewBag.Details.Email" type="text" maxlength="16" class="card-number-input" asp-for="Email">
                </div>
                <div class="inputBox">
                    <span>
                        Địa chỉ
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>
                    <input type="text" class="text-input" value="@ViewBag.Details.DiaChi" type="text" class="card-holder-input" asp-for="DiaChi">

                </div>
                <div class="inputBox">
                    <span>
                        Ngày Tạo
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>
                    <input type="text" class="text-input" value="@ViewBag.Details.NgayTao" type="text" class="card-holder-input" asp-for="NgayTao">

                </div>
                <div class="inputBox">
                    <span>
                        Mật Khẩu
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>
                    <input type="text" class="text-input" value="@ViewBag.Details.MatKhau" type="text" class="card-holder-input" asp-for="MatKhau">

                </div>
            </div>
            <div class="flexbox">
                

            </div>

        </form>

    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".toggleButton").click(function () {
                var input = $(this).prev();
                if (input.attr("type") == "password") {
                    input.attr("type", "text");
                } else {
                    input.attr("type", "password");
                }
            });
        });
    </script>


</div>

Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Views/Customer/EditCustomer.cshtml
@using Web_CNPMNC_DA_HeThongATM.Models.ViewModel

@model KhachHangViewModel
	Layout = "_LayoutMain";
	var accounts = ViewData["j"] as List<KhachHangViewModel>;
}

<body>
	<form method="post" asp-controller="Customer" asp-action="EditCustomer" class="content" enctype="multipart/form-data">
		<div class="row">
			<div class="col-md-12">
				<div class="card card-primary">
					<div class="card-body">
						<div class="form-group">
							<label for="inputSTK" asp-for="CCCD">Căn Cước Công Dân</label>
							<input type="text" id="inputSTK" class="form-control" asp-for="CCCD">
						</div>
						<div class="form-group">
							<label for="inputSTK" asp-for="TenKH">Tên Khách Hàng</label>
							<input type="text" id="inputSTK" class="form-control" asp-for="TenKH">
						</div>
						<div class="col-md-4">
							<div>
								<label class=" form-control-label">Giới tính</label>

							</div>
							<div>
								<div class="form-check-inline form-check">
									<label for="inline-radio1" class="form-check-label col-md-7">
										<input type="radio" id="inline-radio1" name="Gioitinh" value="Nam" asp-for="GioiTinh" class="form-check-input">Nam
									</label>
									<label for="inline-radio2" class="form-check-label col-md-6">
										<input type="radio" id="inline-radio2" name="Gioitinh" value="Nữ" asp-for="GioiTinh" class="form-check-input">Nữ
									</label>
								</div>
							</div>
						</div>
						<div class="row form-group">
							<div class="col-md-3">
								<label for="sonha" class="form-control-label">Số nhà:</label>
								<input type="text" id="sonha" class="form-control">
							</div>
							<div class="col-md-3">
								<label for="phuongxa" class="form-control-label">Phường/Xã:</label>
								<input type="text" id="phuongxa" class="form-control">
							</div>
							<div class="col-md-3">
								<label for="quanhuyen" class="form-control-label">Quận/Huyện:</label>
								<input type="text" id="quanhuyen" class="form-control">
							</div>
							<div class="col-md-3">
								<label for="tinhthanh" class="form-control-label">Tỉnh/Thành phố:</label>
								<input type="text" id="tinhthanh" class="form-control">
							</div>
							<input type="hidden" asp-for="DiaChi" id="Diachi" class="form-control">
						</div>
						<div class="form-group">
							<label for="inputSTK" asp-for="Email">Email</label>
							<input type="text" id="inputSTK" class="form-control" asp-for="Email">
						</div>
						<div class="form-group">
							<label for="inputSTK" asp-for="NgayTao">Căn Cước Công Dân</label>
							<input type="text" id="inputSTK" class="form-control" asp-for="NgayTao">
						</div>
					</div>
					<!-- /.card-body -->
				</div>
				<!-- /.card -->
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<a asp-controller="CustomerService" asp-action="NapTien" class="btn btn-secondary">Cancel</a>
				<button type="submit" class="btn btn-primary btn-sm">Nạp tiền</button>
			</div>
		</div>
	</form>
</body>

Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Views/Customer/Index.cshtml
@using Web_CNPMNC_DA_HeThongATM.Models.ViewModel
@using PagedList.Mvc;
@using PagedList;
@model KhachHangViewModel
@{
    Layout = "_LayoutMain";
    var custommerList = ViewData["j"] as IEnumerable<KhachHangViewModel>;
}
<body>
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Danh sách khách hàng</strong>
                <div class="card-search col col-md-8" style="margin-right:100px">
                    <div class="input-group">
                        <input type="text" id="search-input" class="form-control" placeholder="Tìm kiếm">
                        <div class="input-group-btn">
                            <button class="btn btn-info" id="search-button">
                                <i class="fa fa-search"></i> Search
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="table-stats order-table ov-h" id="CustomerList">

                <table class="table">
                    <thead>
                        <tr>
                            <th style="width:15%">Mã</th>
                            <th style="width:20%">Tên</th>
                            <th style="width:20%%">Giới Tính</th>
                            <th style="width:15%%">Email</th>
                            <th style="width:10%">SDT</th>
                            <th style="width:15%;text-align:left">Chức Năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in custommerList)
                        {


                            <tr>
                                <td>@item.CCCD</td>
                                <td>@item.TenKH</td>
                                <td>@item.GioiTinh</td>
                                <td>@item.Email</td>
                                <td>@item.SoDienThoai</td>
                                <td>
                                    <a class="btn btn-primary" asp-controller="Customer" asp-action="DetailsCustomer" asp-route-CCCD="@item.CCCD">
                                            
                                        <i class="far fa-eye"></i>
                                    </a>
                                </td>
                            </tr>

                        }

                    </tbody>
                </table>
                <div style="text-align:center">
                    @*Trang @(custommerList.PageCount < custommerList.PageNumber ? 0 : custommerList.PageNumber) / @custommerList.PageCount

                    @if (custommerList.HasPreviousPage)
                    {
                        <button class="btn btn-success" onclick="location.href='@Url.Action("Index", new { page = 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })'">
                            <i class="fa-solid fa-angles-right fa-rotate-180"></i>
                        </button>
                        <button class="btn btn-success" onclick="location.href='@Url.Action("Index", new { page = custommerList.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })'">
                            <i class="fa-solid fa-angle-right fa-rotate-180"></i>
                        </button>
                    }

                    @if (custommerList.HasNextPage)
                    {
                        <button class="btn btn-success" onclick="location.href='@Url.Action("Index", new { page = custommerList.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })'">
                            <i class="fa-solid fa-angle-right"></i>
                        </button>
                        <button class="btn btn-success" onclick="location.href='@Url.Action("Index", new { page = custommerList.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })'">
                            <i class="fa-solid fa-angles-right"></i>
                        </button>
                    }*@
                </div>

            </div>
            <div class="table-stats order-table ov-h" id="SearchCustomerID">
            </div><!-- /.table-stats -->
        </div>
    </div>
    <script src="/js/ListCustomer.js"></script>
    <script src="/js/Typescript/fromcard.js"></script>
</body>

Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Views/Customer/SearchCustomer.cshtml
<div class="table-stats order-table ov-h">
    <table class="table">
        <thead>
            <tr>
                <th style="width:10%">Mã</th>
                <th style="width:15%">Tên</th>
                <th style="width:15%">NgayTao</th>
                <th style="width:15%%">Email</th>
                <th style="width:10%">SDT</th>
                <th style="width:15%%">Giới Tính</th>
                <th style="width:20%;text-align:left">Địa chỉ</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@ViewBag.IteamSeach.CCCD</td>
                <td>@ViewBag.IteamSeach.TenKH</td>
                <td>@ViewBag.IteamSeach.NgayTao</td>
                <td>@ViewBag.IteamSeach.Email</td>
                <td>@ViewBag.IteamSeach.SoDienThoai</td>
                <td>@ViewBag.IteamSeach.GioiTinh</td>
                <td>@ViewBag.IteamSeach.DiaChi</td>
            </tr>
        </tbody>
    </table>
</div>