Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Controllers/TransferMoneyController.cs
using Microsoft.AspNetCore.Mvc;
using Web_CNPMNC_DA_HeThongATM.Models;
using Web_CNPMNC_DA_HeThongATM.Models.ClassModel;
using Web_CNPMNC_DA_HeThongATM.Models.ViewModel;

namespace Web_CNPMNC_DA_HeThongATM.Controllers
{
    
    public class TransferMoneyController : Controller
    {
        FirebaseHelper firebaseHelper = new FirebaseHelper();
        string TenTK;
        string accountKey;
        string TenTK1;
        public IActionResult Index()
        {

            return View();
        }
        [HttpGet]
        public IActionResult sendAccount(long SoTaiKhoan)
        {
            string tinhtrang = "undefined";
            if (firebaseHelper.GetAccountbyid(SoTaiKhoan) != null)
            {
                TenTK = firebaseHelper.GetAccountbyid(SoTaiKhoan).TenTK;
                return Json(TenTK);              
            }
            else
            {
                return Json("Không tìm thấy");
            }
        }

        public IActionResult ChuyenTien(IFormCollection form)
        {
            // Lấy dữ liệu từ form
            double soTien = Convert.ToDouble(form["SoTien"]);
            long taiKhoanNguoiChuyen = Convert.ToInt64(form["SoTaiKhoanNguoiChuyen"]);
            long taiKhoanNguoiNhan = Convert.ToInt64(form["SoTaiKhoanNguoiNhan"]);

            // Tiếp tục xử lý chuyển tiền
            firebaseHelper.ChuyenTien(soTien, taiKhoanNguoiChuyen, taiKhoanNguoiNhan);

            ViewData["ChuyenTienSuccess"] = true;

            return RedirectToAction("Index");
        }

        }
}

Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Views/WithdrawMoney/Index.cshtml
@using Web_CNPMNC_DA_HeThongATM.Models.ViewModel

@model TaiKhoanLienKetViewModel
@{
    Layout = "_LayoutMain";
    var aben = ViewData["aben"] as IEnumerable<TaiKhoanLienKetViewModel>;
    var disableButton = ViewData["aben"] == null;
}

<body>
   

    <div class="formbold-main-wrapper">
        <div class="w-full">
            <div class="formbold-form-wrapper">
                <div class="formbold-form-header">
                    <h3>Rút tiền</h3>
                </div>
                <form method="post" asp-controller="WihtdrawMoney" asp-action="RutTien"
                      class="formbold-chatbox-form">
                    <div class="formbold-mb-5">
                        <label for="stk" class="formbold-form-label"> Số tài khoản người rút </label>
                        <input id="SoTaiKhoan" type="text" asp-for="SoTaiKhoan" aria-required="true" aria-invalid="false"
                               placeholder="Nhập số tài khoản"
                               class="formbold-form-input" />
                    </div>
                    <div class="formbold-mb-5">
                        <label for="email" class="formbold-form-label"> Họ và tên chủ tài khoản </label>
                        <input id="tenTK" type="text" asp-for="TenTK"
                               placeholder=""
                               class="formbold-form-input" readonly>
                    </div>

                    <div class="formbold-mb-5">
                        <label for="message" class="formbold-form-label"> Số tiền </label>
                        <input type="text" asp-for="SoTien"
                               placeholder="1.000.000"
                               class="formbold-form-input" >
                        </input>
                    </div>

                    <div>
                        <button asp-controller="TransferMoney" asp-action="ChuyenTien" class="formbold-btn w-full">Rút tiền</button>
                    </div>
                </form>

            </div>
        </div>

        <style>
            .formbold-main-wrapper {
                display: flex;
                align-items: center;
                justify-content: center;
                padding: 48px;
            }
           
            .formbold-form-header {
                background: #6a64f1;
                display: flex;
                align-items: center;
                justify-content: space-between;
                padding: 12px 36px;
                border-radius: 8px 8px 0px 0px;
            }

                .formbold-form-header h3 {
                    font-weight: 700;
                    font-size: 20px;
                    color: white;
                }

            .formbold-chatbox-form {
                padding: 32px 36px;
            }

            .formbold-mb-5 {
                margin-bottom: 20px;
            }

            .formbold-form-label {
                display: block;
                font-weight: 500;
                font-size: 16px;
                color: #07074d;
                margin-bottom: 12px;
            }

            .formbold-form-label-2 {
                font-weight: 600;
                font-size: 20px;
                margin-bottom: 20px;
            }

            .formbold-form-input {
                width: 100%;
                padding: 12px 24px;
                border-radius: 6px;
                border: 1px solid #e0e0e0;
                background: white;
                font-weight: 500;
                font-size: 16px;
                color: #6b7280;
                outline: none;
                resize: none;
            }

                .formbold-form-input:focus {
                    border-color: #6a64f1;
                    box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
                }

            * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }

            body {
                font-family: "Inter", sans-serif;
            }

            .formbold-pt-3 {
                padding-top: 12px;
            }

            .formbold-form-wrapper.active {
                display: block;
            }

            .formbold-form-label {
                display: block;
                font-weight: 500;
                font-size: 16px;
                color: #07074d;
                margin-bottom: 12px;
            }

            .formbold-form-label-2 {
                font-weight: 600;
                font-size: 20px;
                margin-bottom: 20px;
            }

            .formbold-btn {
                text-align: center;
                font-size: 16px;
                border-radius: 6px;
                padding: 14px 32px;
                border: none;
                font-weight: 600;
                background-color: #6a64f1;
                color: white;
                cursor: pointer;
            }

                .formbold-btn:hover {
                    box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
                }

            .formbold--mx-3 {
                margin-left: -12px;
                margin-right: -12px;
            }

            .formbold-px-3 {
                padding-left: 12px;
                padding-right: 12px;
            }

            .flex {
                display: flex;
            }

            .flex-wrap {
                flex-wrap: wrap;
            }

            .w-full {
                width: 50%;
            }

            .formbold-form-header button {
                color: white;
                background: transparent;
                border: none;
            }

            .formbold-action-buttons {
                max-width: 550px;
                margin-left: auto;
                margin-right: auto;
                display: flex;
                align-items: center;
                justify-content: flex-end;
                margin-top: 48px;
            }

            .formbold-action-btn {
                width: 70px;
                height: 70px;
                background: #6a64f1;
                color: white;
                border-radius: 50%;
                margin-left: 20px;
                border: none;
                cursor: pointer;
                display: flex;
                align-items: center;
                justify-content: center;
            }

                .formbold-action-btn .formbold-cross-icon {
                    display: none;
                }

                .formbold-action-btn.active .formbold-cross-icon {
                    display: block;
                }

                .formbold-action-btn.active .formbold-chat-icon {
                    display: none;
                }
        </style>

        <script src="/js/RutChuyenTien.js">
        
        </script>

</body>