Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Controllers/SaveMoneyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Drawing;
using System.Globalization;
using Web_CNPMNC_DA_HeThongATM.Models;
using Web_CNPMNC_DA_HeThongATM.Models.ClassModel;
using Web_CNPMNC_DA_HeThongATM.Models.ViewModel;

namespace Web_CNPMNC_DA_HeThongATM.Controllers
{
    public class SaveMoneyController : Controller
    {
        FirebaseHelper firebaseHelper = new FirebaseHelper();

        private string Day()
        {
            // Lấy ngày tháng năm hiện tại
            DateTime currentDate = DateTime.Now;

            // Lấy ngày
            int day = currentDate.Day;

            // Lấy tháng
            int month = currentDate.Month;

            // Lấy năm
            int year = currentDate.Year;
            return day + "/" + month + "/" + year;
        }
        public IActionResult OpenSavingsHome()
        {
            ViewBag.OpenSavingsHome = firebaseHelper.GetNameLaiSuat();
            return View();

        }


        [HttpGet]
        public IActionResult getInfomationCus(long sotaikhoannguon)
        {
            TaiKhoanLienKet taiKhoanLien = firebaseHelper.GetTaiKhoanLienKetSTK(sotaikhoannguon);
            return Json(taiKhoanLien);
        }
        [HttpPost]
        public IActionResult SaveMoney(GuiTietKiemViewModel guiTietKiem)
        {
            GiaoDich giaoDich;
            //xử lý mật khẩu nhân viên tại đây



            //sử lý trừ tiền

            ModelState.Remove("Key");
            ModelState.Remove("NgayGui");
            ModelState.Remove("TienLaiKyHan");
            ModelState.Remove("TaiKhoanLienKet");
            if (ModelState.IsValid)
            {
                TaiKhoanLienKet taiKhoan = JsonConvert.DeserializeObject<TaiKhoanLienKet>(guiTietKiem.TaiKhoanLienKet);


                GuiTietKiem tietKiemk = new GuiTietKiem
                {
                    Key = "",
                    TaiKhoanTietKiem = 0,
                    MaKHKey = taiKhoan.MaKHKey,
                    TaiKhoanNguon = taiKhoan.SoTaiKhoan,
                    LaiSuatKey = guiTietKiem.LaiSuatKey,
                    NgayGui = Day(),
                    TienLaiToiKy = 0,
                    TienGui = (double)guiTietKiem.TienGui
                };


                JObject data = JObject.Parse(guiTietKiem.TaiKhoanLienKet);
                giaoDich = new GiaoDich
                {
                    Key = "",
                    GioGiaoDich = DateTime.Now.ToString("HH:mm:ss"),
                    NgayGiaoDich = Day(),
                    LoaiGiaoDichKey = "1",
                    NoiDungChuyenKhoan = "Nạp tiền tài khoản tiết kiệm",
                    PhiGiaoDich = (double)guiTietKiem.TienGui * 0.001,
                    SoDuLucGui = (double)data["soDu"],
                    SoTienGiaoDich = (double)guiTietKiem.TienGui,
                    SoDuLucNhan = (double)data["soDu"] - (double)guiTietKiem.TienGui,
                    TaiKhoanNguon = (long)data["soTaiKhoan"],
                    TaiKhoanNhan = guiTietKiem.TaiKhoanTietKiem,
                };

                firebaseHelper.GuiTietKiem(tietKiemk, taiKhoan);



                firebaseHelper.LichSuGD("1", giaoDich);
                TempData["Message"] = "Gửi tiết kiệm";
                return RedirectToAction("OpenSavingsHome");
            }
            ViewBag.OpenSavingsHome = firebaseHelper.GetNameLaiSuat();
            TempData["Fail"] = "Gửi tiết kiệm";
            return View("OpenSavingsHome", guiTietKiem);
        }
        //tất toán tiết kiệm
        [HttpGet]
        public IActionResult SettlementOfSavings()
        {

            return View();
        }

        [HttpPost]
        public IActionResult SettlementOfSavings(GuiTietKiemViewModel guiTietKiemView)
        {

            ModelState.Remove("Key");
            ModelState.Remove("NgayGui");
            ModelState.Remove("TienLaiKyHan");
            ModelState.Remove("TaiKhoanLienKet");
            ModelState.Remove("LaiSuatKey");
            ModelState.Remove("TienLaiKyHan");
            ModelState.Remove("TienGui");
            if (ModelState.IsValid)
            {
                JObject data = JObject.Parse(guiTietKiemView.TaiKhoanLienKet);
                //lấy kì hạn
                string kihan = (string)data["laiSuat"]["kyHan"];
                //lấy ngày gửi theo số tài khoản tiết kiểm
                string ngaygui = (string)data["guiTietKiem"]["ngayGui"];
                //bước lấy số tiền tiết kiệm tiền lãi + tới kỳ
                double tienrut = (double)data["guiTietKiem"]["tienGui"] + (double)data["guiTietKiem"]["tienLaiToiKy"];
                long taikhoanng = (long)data["guiTietKiem"]["taiKhoanNguon"];
                string taikhoantietkiem = (string)data["guiTietKiem"]["key"];
                //kiểm tra ngày gửi đúng lấy số tiền lãi sai thì thông báo không thể tất toán đợi đến ngày .... 
                //nếu rút thành công thì lưu lịch sử và xóa sổ tiết kiệm
                DateTime futureDate;
                if (CompareDate(ngaygui, kihan, out futureDate))
                {

                    firebaseHelper.TatToanTietKiem(taikhoanng, taikhoantietkiem,tienrut);
                  GiaoDich  giaoDich = new GiaoDich
                    {
                        Key = "",
                        GioGiaoDich = DateTime.Now.ToString("HH:mm:ss"),
                        NgayGiaoDich = Day(),
                        LoaiGiaoDichKey = "1",
                        NoiDungChuyenKhoan = "Rút hết tiền tài khoản tiết kiệm",
                        PhiGiaoDich = (double)guiTietKiemView.TienGui * 0.001,
                        SoDuLucGui = (double)data["guiTietKiem"]["tienGui"],
                        SoDuLucNhan = (double)data["guiTietKiem"]["tienGui"]+tienrut,
                        SoTienGiaoDich = tienrut,
                        TaiKhoanNguon = (long)data["guiTietKiem"]["taiKhoanTietKiem"],
                        TaiKhoanNhan = (long)data["guiTietKiem"]["taiKhoanNguon"],
                    };
                    firebaseHelper.LichSuGD("2", giaoDich);
                    TempData["Message"] = "Tất toán";
                    return RedirectToAction("SettlementOfSavings");
                }
                else
                {
                    TempData["Fail"] = "Chỉ rút được sau ngày " + futureDate.ToString();
                    View("SettlementOfSavings", guiTietKiemView);
                }


            }
            return View("SettlementOfSavings", guiTietKiemView);
        }
        //nạp tiết kiệm
        [HttpGet]
        public IActionResult GetTKNorTKTK(long stk)
        {
            GuiTietKiem guiTietKiem = firebaseHelper.GetAccontSaveMoney(stk);
            LaiSuat laiSuat = firebaseHelper.GetLaiSuat(guiTietKiem.LaiSuatKey);
            TaiKhoanLienKet taiKhoanLien = firebaseHelper.GetTaiKhoanLienKetSTK(guiTietKiem.TaiKhoanNguon);
            DateTime futureDate;
            CompareDate(guiTietKiem.NgayGui, laiSuat.KyHan,out futureDate);
            
            var data = new
            {
                guiTietKiem,
                laiSuat,
                taiKhoanLien.TenTK,
                ngayduocrut = futureDate.ToString(),

            };
            return Json(data);
        }


        [HttpGet]
        public IActionResult AdmitMoney()
        {

            return View();
        }

        [HttpPost]
        public IActionResult AdmitMoney(GuiTietKiemViewModel guiTietKiemView)
        {
            GiaoDich giaoDich;
            ModelState.Remove("Key");
            ModelState.Remove("NgayGui");
            ModelState.Remove("TienLaiKyHan");
            ModelState.Remove("TaiKhoanLienKet");
            ModelState.Remove("LaiSuatKey");
            ModelState.Remove("TienLaiKyHan");
            ModelState.Remove("TaiKhoanNguon");
            if (guiTietKiemView.TaiKhoanLienKet != null && ModelState.IsValid)
            {
                JObject data = JObject.Parse(guiTietKiemView.TaiKhoanLienKet);



                if (firebaseHelper.AdmitSaveMoney((double)guiTietKiemView.TienGui, (string)data["guiTietKiem"]["key"]))
                {


                    giaoDich = new GiaoDich
                    {
                        Key = "",
                        GioGiaoDich = DateTime.Now.ToString("HH:mm:ss"),
                        NgayGiaoDich = Day(),
                        LoaiGiaoDichKey = "1",
                        NoiDungChuyenKhoan = "Nạp tiền tài khoản tiết kiệm",
                        PhiGiaoDich = (double)guiTietKiemView.TienGui * 0.001,
                        SoDuLucGui = (double)data["guiTietKiem"]["tienGui"],
                        SoDuLucNhan = (double)data["guiTietKiem"]["tienGui"] + (double)guiTietKiemView.TienGui,
                        SoTienGiaoDich = (double)guiTietKiemView.TienGui,
                        TaiKhoanNguon = (long)data["guiTietKiem"]["taiKhoanNguon"],
                        TaiKhoanNhan = (long)data["guiTietKiem"]["taiKhoanTietKiem"],
                    };
                    firebaseHelper.LichSuGD("4", giaoDich);
                    TempData["Message"] = "Gửi tiết kiệm";
                    return RedirectToAction("AdmitMoney");



                }
            }

            TempData["Fail"] = "Gửi tiết kiệm";
            return View("AdmitMoney", guiTietKiemView);
        }

        //check ngày để rút
        public bool CompareDate(string dateString, string kihan, out DateTime futureDate)
        {
            DateTimeFormatInfo dtfi = new DateTimeFormatInfo();
            dtfi.ShortDatePattern = "MM/dd/yyyy";
            dtfi.DateSeparator = "/";
            DateTime objDate = Convert.ToDateTime(dateString, dtfi);

            string[] parts = kihan.Split(' ');
            string numberPart = parts[0];
            // Thêm tháng vào ngày
            futureDate = objDate.AddMonths(int.Parse(numberPart));

            // So sánh với ngày hiện tại

Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Views/SaveMoney/AdmitMoney.cshtml
@using Web_CNPMNC_DA_HeThongATM.Models.ViewModel
@model GuiTietKiemViewModel
@{
    Layout = "_LayoutMain";
    var laixuat = ViewBag.OpenSavingsHome;
}

@if (TempData["Message"] != null)
{
    <div class="sufee-alert alert with-close alert-primary alert-dismissible fade show">
        <span class="badge badge-pill badge-primary">Thành Công</span>
        @TempData["Message"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
}
else if (TempData["Fail"] != null)
{
    <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
        <span class="badge badge-pill badge-danger">Thất Bại</span>
        @TempData["Fail"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
}
<div class="col-md-12" style=" height:100vh;">
    <h6 class="title col-md-12">
       Nạp Tiền Tiết Kiệm
    </h6>
    <div class="container col-md-7" style="display:-webkit-inline-box;">
        <form method="post" asp-controller="SaveMoney" asp-action="AdmitMoney" style="padding-top:0px ; background-color:#ffff">

            <div class="flexbox">

                <div class="inputBox">
                    <span>
                        Tài Khoản Nguồn/Tiết Kiệm
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>

                </div>
                <div class="inputBox">
                    <input asp-for="TaiKhoanNguon" value="" type="text" maxlength="16" id="InputTaiKhoanNguon">
                    <span asp-validation-for="TaiKhoanNguon" class="text-danger"></span>
                </div>
            </div>         
            <div class="flexbox">

                <div class="inputBox">
                    <span>
                        Số tiền nạp
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>

                </div>
                <div class="inputBox">
                    <input asp-for="TienGui" id="sotiengui" value="" type="text" maxlength="16">
                    <span asp-validation-for="TienGui" class="text-danger"></span>
                </div>    
                </div>
            <div class="flexbox">

                <div class="inputBox">
                    <span>
                        Nhập Mật Khẩu Nhân Viên
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>

                </div>
                <div class="inputBox">
                    <input value="" type="text" maxlength="16">
                </div>
            </div>
            <div class="flexbox">
                <input id="datataikhoan" asp-for="TaiKhoanLienKet" hidden type="text" />
                <input type="submit" value="Nạp tiền" class="submit-btn">
            </div>

        </form>
        @* //card *@
        <div class="card col-md-8 name-label">
            <div class="twt-feed blue-bg">

                <div class="media">
                    <a href="#">
                        <img class="align-self-center rounded-circle mr-3" style="width:85px; height:85px;" alt="" src="/images/admin.jpg">
                    </a>
                    <div class="media-body">
                        <h3 class="text-white display-6"><span class="ti-user"></span> KHÁCH HÀNG</h3>
                        <h6 class="text-light" id="tenkhachhang"></h6>


                    </div>
                </div>
            </div>


            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="#">
                        Số tài khoản tiết kiệm:&nbsp;&nbsp;
                        <span id="sotaikhoan"></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        Số tiền gửi: &nbsp;&nbsp;&nbsp;
                        <span id="sodu"></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        Ngày Gửi: &nbsp;&nbsp;&nbsp;
                        <span id="NgayGui"></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        Kỳ Hạn: &nbsp;&nbsp;&nbsp;
                        <span id="kyhan"></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        Tỉ Lệ: &nbsp;&nbsp;&nbsp;
                        <span id="tile"></span>
                    </a>
                </li>
            </ul>
        </div>

    </div>
</div>

<script src="~/js/AdmitMoney.js">

</script>

Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Views/SaveMoney/OpenSavingsHome.cshtml
@using Web_CNPMNC_DA_HeThongATM.Models.ViewModel
@model GuiTietKiemViewModel
@{
    Layout = "_LayoutMain";
    var laixuat = ViewBag.OpenSavingsHome;
}


@if (TempData["Message"] != null)
{
    <div class="sufee-alert alert with-close alert-primary alert-dismissible fade show">
        <span class="badge badge-pill badge-primary">Thành Công</span>
        @TempData["Message"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
}
else if(TempData["Fail"]!= null)
{
    <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
        <span class="badge badge-pill badge-danger">Thất Bại</span>
        @TempData["Fail"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
}

<div class="col-md-12" style=" height:100vh;">
    <h6 class="title col-md-12">
        MỞ TÀI KHOẢN TIẾT KIỆM
    </h6>
    <div class="container col-md-7" style="display:-webkit-inline-box;">
        <form method="post" asp-controller="SaveMoney" asp-action="SaveMoney" style="padding-top:0px ; background-color:#ffff">

            <div class="flexbox">

                <div class="inputBox">
                    <span>
                        Tài Khoản Nguồn
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>

                </div>
                <div class="inputBox">
                    <input asp-for="TaiKhoanNguon"  value="" type="text" maxlength="16" id="InputTaiKhoanNguon">
                    <span asp-validation-for="TaiKhoanNguon" class="text-danger"></span>
                </div>
            </div>
            <div class="flexbox">

                <div class="inputBox">
                    <span>
                        Kỳ hạn gửi
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>

                </div>
                <div class="inputBox">           
                    <select asp-for="LaiSuatKey" class="type-card">
                        <option selected disabled>Chọn lãi suất</option>
                        @foreach(var item in laixuat)
                        {
                            string name = item.KyHan + " (" + item.TiLe + "%)";
                            <option value="@item.Key">@name</option>
                        }
                        
                    </select>
                    <span asp-validation-for="LaiSuatKey" class="text-danger"></span>
                </div>
            </div>
            <div class="flexbox">

                <div class="inputBox">
                    <span>
                        Số tiền gửi
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>

                </div>
                <div class="inputBox">
                    <input asp-for="TienGui" id="sotiengui" value="" type="text" maxlength="16" >
                    <span asp-validation-for="TienGui" class="text-danger"></span>
                </div>
            </div>
            <div class="flexbox">

                <div class="inputBox">
                    <span>
                        Hình thức trả lãi
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>

                </div>
                <div class="inputBox">
                    <select class="type-card">
                        <option value="Loại" selected disabled>Loại</option>
                        <option>lãi nhập góc</option>
                        <option>lãi trả vào tài khoản tiền gửi khi đến hạn trả lãi</option>
                    </select>
                </div>
                </div>
            <div class="flexbox">

                <div class="inputBox">
                    <span>
                        Nhập Mật Khẩu Nhân Viên
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>

                </div>
                <div class="inputBox">
                    <input  value="" type="text" maxlength="16">
                </div>
            </div>
            <div class="flexbox">
                <input id="datataikhoan" asp-for="TaiKhoanLienKet" hidden type="text" />
                <input type="submit" value="submit" class="submit-btn">
            </div>
          
        </form>
        @* //card *@
        <div class="card col-md-8 name-label">
            <div class="twt-feed blue-bg">
       
                <div class="media">
                    <a href="#">
                        <img class="align-self-center rounded-circle mr-3" style="width:85px; height:85px;" alt="" src="/images/admin.jpg">
                    </a>
                    <div class="media-body">
                        <h3 class="text-white display-6"><span class="ti-user"></span> KHÁCH HÀNG</h3>                     
                        <h6 class="text-light" id="tenkhachhang"></h6>
                       
                        
                    </div>
                </div>
            </div>


            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="#">
                        Số tài khoản:&nbsp;&nbsp;&nbsp;
                        <span id="sotaikhoan"></span></a>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        Số dư khả dụng: &nbsp;&nbsp;&nbsp;
                        <span id="sodu"></span>
                    </a>
                </li>
               
            </ul>
        </div>

    </div>
   </div>

    <script src="/js/LaiSuat.js">
       
    </script>

Web_CNPMNC_DA_HeThongATM/Web_CNPMNC_DA_HeThongATM/Views/SaveMoney/SettlementOfSavings.cshtml
@using Web_CNPMNC_DA_HeThongATM.Models.ViewModel
@model GuiTietKiemViewModel
@{
    Layout = "_LayoutMain";
  
}

@if (TempData["Message"] != null)
{
    <div class="sufee-alert alert with-close alert-primary alert-dismissible fade show">
        <span class="badge badge-pill badge-primary">Thành Công</span>
        @TempData["Message"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
}
else if (TempData["Fail"] != null)
{
    <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
        <span class="badge badge-pill badge-danger">Thất Bại</span>
        @TempData["Fail"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
}
<div class="col-md-12" style=" height:100vh;">
    <h6 class="title col-md-12">
        Rút Tiền Tiết Kiệm
    </h6>
    <div class="container col-md-7" style="display:-webkit-inline-box;">
        <form method="post" asp-controller="SaveMoney" asp-action="SettlementOfSavings" style="padding-top:0px ; background-color:#ffff">
            <div style="display:none" id="alertnote" class="alert alert-danger" role="alert">
                <h4 class="alert-heading">Lưu ý!</h4>
                <p id="alertcontent"></p>
               
                
            </div>
            <div class="flexbox">

                <div class="inputBox">
                    <span>
                        Tài Khoản Nguồn/Tiết Kiệm
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>

                </div>
                <div class="inputBox">
                    <input asp-for="TaiKhoanNguon" value="" type="text" maxlength="16" id="InputTaiKhoanNguon">
                    <span asp-validation-for="TaiKhoanNguon" class="text-danger"></span>
                </div>
            </div>
           @*  <div class="flexbox">

                <div class="inputBox">
                    <span>
                        Số tiền rút
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>

                </div>
                <div class="inputBox">
                    <input asp-for="TienGui" id="sotiengui" value="" type="text" maxlength="16">
                    <span asp-validation-for="TienGui" class="text-danger"></span>
                </div>
            </div> *@
            <div class="flexbox">

                <div class="inputBox">
                    <span>
                        Nhập Mật Khẩu Nhân Viên
                        <i class="fa-solid fa-pen-to-square"></i>
                    </span>

                </div>
                <div class="inputBox">
                    <input value="" type="text" maxlength="16">
                </div>
            </div>
            <div class="flexbox">
                <input id="datataikhoan" asp-for="TaiKhoanLienKet" hidden type="text" />
                <input  id="OutTien" type="submit" value="Rút Tiền" class="submit-btn">
               
            </div>

        </form>
        @* //card *@
        <div class="card col-md-8 name-label">
            <div class="twt-feed blue-bg">

                <div class="media">
                    <a href="#">
                        <img class="align-self-center rounded-circle mr-3" style="width:85px; height:85px;" alt="" src="/images/admin.jpg">
                    </a>
                    <div class="media-body">
                        <h3 class="text-white display-6"><span class="ti-user"></span> KHÁCH HÀNG</h3>
                        <h6 class="text-light" id="tenkhachhang"></h6>


                    </div>
                </div>
            </div>


            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="#">
                        Số tài khoản tiết kiệm:&nbsp;&nbsp;
                        <span id="sotaikhoan"></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        Số tiền gửi: &nbsp;&nbsp;&nbsp;
                        <span id="sodu"></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        Số tiền lãi: &nbsp;&nbsp;&nbsp;
                        <span id="tienlai"></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        Ngày Gửi: &nbsp;&nbsp;&nbsp;
                        <span id="NgayGui"></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        Kỳ Hạn: &nbsp;&nbsp;&nbsp;
                        <span id="kyhan"></span>
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        Tỉ Lệ: &nbsp;&nbsp;&nbsp;
                        <span id="tile"></span>
                    </a>
                </li>
              
            </ul>
        </div>

    </div>
</div>

<script src="~/js/SettlemenOfSaving.js">

</script>